plugins:
- jekyll-remote-theme

remote_theme: tuur29/pages-themes-cayman

show_downloads: false
darkmode: True
color:
    gradient_left: "#ffaa00"
    gradient_right: "#e32759"
    header: "#fff"
buttons:
    github_hide: true
